version: '3.1'
services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: USER
      MONGO_INITDB_ROOT_PASSWORD: PASS
  node:
    container_name: node
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app   
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "yarn start"
    
 